### ISSUE TITLE
Analytics Update

### ISSUE THREAD

**Issue by judemanutd** [GlennFernandes/octa-react-portal#69]
Analytics is currently initialized in the app but in order to capture specific events, it needs to be used on-page. 

https://github.com/GlennFernandes/octa-react-portal/blob/21ec2950fffbb9353166892f26aca768c87e04e5/src/pages/Portfolio/index.js#L237-L241

https://github.com/GlennFernandes/octa-react-portal/blob/21ec2950fffbb9353166892f26aca768c87e04e5/src/pages/Portfolio/index.js#L249-L252

In order to call those lines, the `analytics` object from firebase needs to be used which is available in the `app.js` file. Store it in redux maybe so it can be used wherever needed?

**Comment by judemanutd** [comment]
@GlennFernandes

**Comment by GlennFernandes** [comment]
where do i get item from?

**Comment by judemanutd** [comment]
https://github.com/GlennFernandes/octa-react-portal/blob/21ec2950fffbb9353166892f26aca768c87e04e5/src/pages/Portfolio/index.js#L235-L246

@GlennFernandes `data.components` has all the components that were fetched so `item` is just each item that is viewed by the user, keeping track of what they saw. 

```
 analytics.logEvent("view_item", {
              content_type: destination.anchor,
              name: destination.anchor,
            });
```
To log when the view footer or header
